export const WEBHOOK_URL = 'webhook-url'
export const CONTENT = 'content'
export const USERNAME = 'username'
export const AVATAR_URL = 'avatar-url'
export const RAW_DATA = 'raw-data'
export const RAW_STRING = 'raw-string'
export const TITLE = 'title'
export const DESCRIPTION = 'description'
export const TIMESTAMP = 'timestamp'
export const COLOR = 'color'
export const NAME = 'name'
export const URL = 'url'
export const ICON_URL = 'icon-url'
export const TEXT = 'text'
export const FILENAME = 'filename'
export const THREAD_ID = 'thread-id'
export const THREAD_NAME = 'thread-name'
export const FLAGS = 'flags'

export const TOP_LEVEL_WEBHOOK_KEYS = [CONTENT, USERNAME, AVATAR_URL]
export const EMBED_KEYS = [TITLE, DESCRIPTION, TIMESTAMP, COLOR, URL]
export const EMBED_AUTHOR_KEYS = [NAME, URL, ICON_URL]
export const EMBED_FOOTER_KEYS = [TEXT, ICON_URL]
export const EMBED_IMAGE_KEYS = [URL]
export const EMBED_THUMBNAIL_KEYS = [URL]