name: Self Invoke

on:
  workflow_dispatch:
    inputs:
      webhook:
        description: 'Webhook URL'
        type: string
        required: true

jobs:
  self_invoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Self Invoke
        uses: ./
        with:
          webhook-url: ${{ inputs.webhook }}
          username: ${{ github.event.sender.name }}
          avatar-url: ${{ github.event.sender.avatar_url }}

          embed-color: 0x33b4ff
          embed-title: Self invoke (${{ github.actor }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>)
          embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          embed-image-url: https://emojiapi.dev/api/v1/framed_picture.svg
          embed-thumbnail-url: https://emojiapi.dev/api/v1/rocket.svg

          embed-author-name: ${{ github.actor.name }}
          embed-author-url: ${{ github.event.sender.avatar_url }}
          embed-author-icon-url: ${{ github.event.sender.avatar_url }}

          embed-description: |
            [${{ github.workflow }} \#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            [${{ env.GIT_COMMIT_SHORT_SHA }}](${{ github.server_url }}/${{ github.repository }}/${{ github.sha }})

            > ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"

            > ${{ env.GIT_COMMIT_MESSAGE_BODY }}

          embed-footer-text: Job id `${{ github.job }}`
          embed-footer-icon-url: https://emojiapi.dev/api/v1/bullseye.svg
