name: Self Invoke

on:
  workflow_dispatch:
    inputs:
      webhook:
        description: 'Webhook URL'
        type: string
        required: true

jobs:
  self_invoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Self Invoke
        uses: ./
        with:
          webhook-url: ${{ inputs.webhook }}
          username: ${{ github.event.sender.name }}
          avatar-url: ${{ github.event.sender.avatar_url }}

          embed-color: 0x33b4ff
          embed-title: Self Invoke [commit#${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/${{ github.sha }}) run by ${{ github.actor }} ${{ github.event.sender.name }} <${{ github.event.sender.email }}>
          embed-author-name: ${{ github.actor.name }}
          embed-author-icon-url: ${{ github.event.sender.avatar_url }}
          embed-description: "[${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-footer-text: Job id \`${{ github.job }}\`