name: Self Invoke

on:
  workflow_dispatch:
    inputs:
      webhook:
        description: 'Webhook URL'
        type: string
        required: true

jobs:
  self_invoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Self Invoke
        uses: ./
        with:
          webhook-url: ${{ inputs.webhook }}

          username: ${{ github.repository }} CI
          avatar-url: https://github.githubassets.com/images/modules/logos_page/Octocat.png

          embed-color: 0x33b4ff
          embed-title: "${{ github.workflow }} #${{ github.run_number }}"
          embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          embed-image-url: https://emojiapi.dev/api/v1/framed_picture/512.png
          embed-thumbnail-url: https://emojiapi.dev/api/v1/rocket/256.png

          embed-author-name: ${{ github.actor.name }}
          embed-author-url: ${{ github.event.sender.avatar_url }}
          embed-author-icon-url: ${{ github.actor.avatar_url }}

          embed-description: |
            [${{ env.GIT_COMMIT_SHORT_SHA }}](${{ github.server_url }}/${{ github.repository }}/${{ github.sha }})

            > **${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}**

            > ${{ env.GIT_COMMIT_MESSAGE_BODY }}

          embed-footer-text: ${{ github.actor }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          embed-footer-icon-url: https://emojiapi.dev/api/v1/bullseye/128.png
