name: 🧪 Tests

on:
  workflow_dispatch:
    inputs:
      webhook-url:
        description: "Webhook URL"
        type: string
        required: false

env:
  INPUT_WEBHOOK-URL: ${{ inputs.webhook-url }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        timeout-minutes: 5
        run: npm install --include=dev

      - name: Run tests
        timeout-minutes: 5
        run: "npm run test:ci"

        # https://chmodcommand.com/chmod-766/
      - name: Chmod reports
        run: |
          ls -l reports
          chmod --changes --recursive a+rwx,g-x,o-x reports
          ls -l reports

      - name: Test Report local
        uses: dorny/test-reporter@v1
        id: test-report
        if: success() || failure()
        with:
          name: Tests Report Local
          path: reports/jest-*.xml
          reporter: jest-junit
