name: 🧪 Tests

on:
  workflow_dispatch:
    inputs:
      webhook-url:
        description: "Webhook URL"
        type: string
        required: false

  # push:
  #   branches:
  #     - main

  # pull_request:
  #   branches:
  #     - main

env:
  offline_log: offline.start.log
  INPUT_WEBHOOK-URL: ${{ inputs.webhook-url }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        timeout-minutes: 5
        run: npm install --include=dev

      - name: Run tests
        timeout-minutes: 5
        run: "npm run test:ci"

      - name: Show Serverless Offline Logs
        if: success() || failure()
        continue-on-error: true
        run: cat $offline_log

      - name: Test Report local
        uses: dorny/test-reporter@v1
        id: test-report
        if: success() || failure()
        with:
          name: Tests Report Local
          path: reports/jest-*.xml
          reporter: jest-junit
